// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisconnectSink(arg1, arg2) {
  return window['go']['awscredssink']['AwsCredentialsSinkController']['DisconnectSink'](arg1, arg2);
}

export function FlowData(arg1, arg2, arg3) {
  return window['go']['awscredssink']['AwsCredentialsSinkController']['FlowData'](arg1, arg2, arg3);
}

export function GetInstanceData(arg1, arg2) {
  return window['go']['awscredssink']['AwsCredentialsSinkController']['GetInstanceData'](arg1, arg2);
}

export function ListConnectedSinks(arg1, arg2, arg3) {
  return window['go']['awscredssink']['AwsCredentialsSinkController']['ListConnectedSinks'](arg1, arg2, arg3);
}

export function NewInstance(arg1, arg2) {
  return window['go']['awscredssink']['AwsCredentialsSinkController']['NewInstance'](arg1, arg2);
}

export function SinkCode() {
  return window['go']['awscredssink']['AwsCredentialsSinkController']['SinkCode']();
}
