// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisconnectSink(arg1, arg2) {
  return window['go']['awscredentialsfile']['AwsCredentialsFileSinkController']['DisconnectSink'](arg1, arg2);
}

export function FlowData(arg1, arg2, arg3) {
  return window['go']['awscredentialsfile']['AwsCredentialsFileSinkController']['FlowData'](arg1, arg2, arg3);
}

export function GetInstanceData(arg1, arg2) {
  return window['go']['awscredentialsfile']['AwsCredentialsFileSinkController']['GetInstanceData'](arg1, arg2);
}

export function ListConnectedSinks(arg1, arg2, arg3) {
  return window['go']['awscredentialsfile']['AwsCredentialsFileSinkController']['ListConnectedSinks'](arg1, arg2, arg3);
}

export function NewInstance(arg1, arg2) {
  return window['go']['awscredentialsfile']['AwsCredentialsFileSinkController']['NewInstance'](arg1, arg2);
}

export function SinkCode() {
  return window['go']['awscredentialsfile']['AwsCredentialsFileSinkController']['SinkCode']();
}

export function WriteProfileCredentials(arg1, arg2) {
  return window['go']['awscredentialsfile']['AwsCredentialsFileSinkController']['WriteProfileCredentials'](arg1, arg2);
}
