// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInstanceData(arg1, arg2) {
  return window['go']['awscredentialsfile']['AwsCredentialsFileController']['GetInstanceData'](arg1, arg2);
}

export function ListInstances(arg1) {
  return window['go']['awscredentialsfile']['AwsCredentialsFileController']['ListInstances'](arg1);
}

export function NewInstance(arg1, arg2) {
  return window['go']['awscredentialsfile']['AwsCredentialsFileController']['NewInstance'](arg1, arg2);
}

export function WriteProfileCredentials(arg1, arg2) {
  return window['go']['awscredentialsfile']['AwsCredentialsFileController']['WriteProfileCredentials'](arg1, arg2);
}
