// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {awscredentialsfile} from '../models';

export function GetInstanceData(arg1:app.Context,arg2:string):Promise<awscredentialsfile.AwsCredentialsFileInstance>;

export function ListInstances(arg1:app.Context):Promise<Array<string>>;

export function NewInstance(arg1:app.Context,arg2:awscredentialsfile.AwsCredentialsFile_NewInstanceCommandInput):Promise<string>;

export function WriteProfileCredentials(arg1:string,arg2:awscredentialsfile.ProfileCreds):Promise<void>;
