// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plumbing} from '../models';
import {app} from '../models';
import {awsidc} from '../models';

export function AddPlumbers(arg1:Array<plumbing.Plumber[github>):Promise<void>;

export function CopyRoleCredentials(arg1:app.Context,arg2:awsidc.AwsIdc_CopyRoleCredentialsCommandInput):Promise<void>;

export function FinalizeRefreshAccessToken(arg1:app.Context,arg2:awsidc.AwsIdc_FinalizeRefreshAccessTokenCommandInput):Promise<void>;

export function FinalizeSetup(arg1:app.Context,arg2:awsidc.AwsIdc_FinalizeSetupCommandInput):Promise<string>;

export function GetInstanceData(arg1:app.Context,arg2:string,arg3:boolean):Promise<awsidc.AwsIdentityCenterCardData>;

export function ListInstances(arg1:app.Context):Promise<Array<string>>;

export function MarkAsFavorite(arg1:app.Context,arg2:string):Promise<void>;

export function RefreshAccessToken(arg1:app.Context,arg2:string):Promise<awsidc.AuthorizeDeviceFlowResult>;

export function SaveRoleCredentials(arg1:app.Context,arg2:awsidc.AwsIdc_SaveRoleCredentialsCommandInput):Promise<void>;

export function Setup(arg1:app.Context,arg2:awsidc.AwsIdc_SetupCommandInput):Promise<awsidc.AuthorizeDeviceFlowResult>;

export function UnmarkAsFavorite(arg1:app.Context,arg2:string):Promise<void>;
