// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPlumbers(arg1) {
  return window['go']['awsidc']['AwsIdentityCenterController']['AddPlumbers'](arg1);
}

export function CopyRoleCredentials(arg1, arg2) {
  return window['go']['awsidc']['AwsIdentityCenterController']['CopyRoleCredentials'](arg1, arg2);
}

export function FinalizeRefreshAccessToken(arg1, arg2) {
  return window['go']['awsidc']['AwsIdentityCenterController']['FinalizeRefreshAccessToken'](arg1, arg2);
}

export function FinalizeSetup(arg1, arg2) {
  return window['go']['awsidc']['AwsIdentityCenterController']['FinalizeSetup'](arg1, arg2);
}

export function GetInstanceData(arg1, arg2, arg3) {
  return window['go']['awsidc']['AwsIdentityCenterController']['GetInstanceData'](arg1, arg2, arg3);
}

export function ListInstances(arg1) {
  return window['go']['awsidc']['AwsIdentityCenterController']['ListInstances'](arg1);
}

export function MarkAsFavorite(arg1, arg2) {
  return window['go']['awsidc']['AwsIdentityCenterController']['MarkAsFavorite'](arg1, arg2);
}

export function RefreshAccessToken(arg1, arg2) {
  return window['go']['awsidc']['AwsIdentityCenterController']['RefreshAccessToken'](arg1, arg2);
}

export function SaveRoleCredentials(arg1, arg2) {
  return window['go']['awsidc']['AwsIdentityCenterController']['SaveRoleCredentials'](arg1, arg2);
}

export function Setup(arg1, arg2) {
  return window['go']['awsidc']['AwsIdentityCenterController']['Setup'](arg1, arg2);
}

export function UnmarkAsFavorite(arg1, arg2) {
  return window['go']['awsidc']['AwsIdentityCenterController']['UnmarkAsFavorite'](arg1, arg2);
}
