// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {awsiamidc} from '../models';

export function FinalizeRefreshAccessToken(arg1:context.Context,arg2:awsiamidc.AwsIamIdc_FinalizeRefreshAccessTokenCommandInput):Promise<void>;

export function FinalizeSetup(arg1:context.Context,arg2:awsiamidc.AwsIamIdc_FinalizeSetupCommandInput):Promise<string>;

export function GetInstanceData(arg1:context.Context,arg2:string,arg3:boolean):Promise<awsiamidc.AwsIdentityCenterCardData>;

export function GetRoleCredentials(arg1:context.Context,arg2:awsiamidc.AwsIamIdc_GetRoleCredentialsCommandInput):Promise<awsiamidc.AwsIdentityCenterAccountRoleCredentials>;

export function ListInstances(arg1:context.Context):Promise<Array<string>>;

export function MarkAsFavorite(arg1:context.Context,arg2:string):Promise<void>;

export function RefreshAccessToken(arg1:context.Context,arg2:string):Promise<awsiamidc.AuthorizeDeviceFlowResult>;

export function Setup(arg1:context.Context,arg2:awsiamidc.AwsIamIdc_SetupCommandInput):Promise<awsiamidc.AuthorizeDeviceFlowResult>;

export function UnmarkAsFavorite(arg1:context.Context,arg2:string):Promise<void>;
