// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FinalizeRefreshAccessToken(arg1, arg2, arg3, arg4) {
  return window['go']['awsiamidc']['AwsIdentityCenterController']['FinalizeRefreshAccessToken'](arg1, arg2, arg3, arg4);
}

export function FinalizeSetup(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['awsiamidc']['AwsIdentityCenterController']['FinalizeSetup'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetInstanceData(arg1) {
  return window['go']['awsiamidc']['AwsIdentityCenterController']['GetInstanceData'](arg1);
}

export function Init(arg1, arg2) {
  return window['go']['awsiamidc']['AwsIdentityCenterController']['Init'](arg1, arg2);
}

export function ListInstances() {
  return window['go']['awsiamidc']['AwsIdentityCenterController']['ListInstances']();
}

export function RefreshAccessToken(arg1) {
  return window['go']['awsiamidc']['AwsIdentityCenterController']['RefreshAccessToken'](arg1);
}

export function Setup(arg1, arg2, arg3) {
  return window['go']['awsiamidc']['AwsIdentityCenterController']['Setup'](arg1, arg2, arg3);
}
