// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FinalizeRefreshAccessToken(arg1, arg2) {
  return window['go']['awsiamidc']['AwsIdentityCenterController']['FinalizeRefreshAccessToken'](arg1, arg2);
}

export function FinalizeSetup(arg1, arg2) {
  return window['go']['awsiamidc']['AwsIdentityCenterController']['FinalizeSetup'](arg1, arg2);
}

export function GetInstanceData(arg1, arg2, arg3) {
  return window['go']['awsiamidc']['AwsIdentityCenterController']['GetInstanceData'](arg1, arg2, arg3);
}

export function GetRoleCredentials(arg1, arg2) {
  return window['go']['awsiamidc']['AwsIdentityCenterController']['GetRoleCredentials'](arg1, arg2);
}

export function ListInstances(arg1) {
  return window['go']['awsiamidc']['AwsIdentityCenterController']['ListInstances'](arg1);
}

export function MarkAsFavorite(arg1, arg2) {
  return window['go']['awsiamidc']['AwsIdentityCenterController']['MarkAsFavorite'](arg1, arg2);
}

export function RefreshAccessToken(arg1, arg2) {
  return window['go']['awsiamidc']['AwsIdentityCenterController']['RefreshAccessToken'](arg1, arg2);
}

export function Setup(arg1, arg2) {
  return window['go']['awsiamidc']['AwsIdentityCenterController']['Setup'](arg1, arg2);
}

export function UnmarkAsFavorite(arg1, arg2) {
  return window['go']['awsiamidc']['AwsIdentityCenterController']['UnmarkAsFavorite'](arg1, arg2);
}
