// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CatchUnhandledError(arg1) {
  return window['go']['main']['AppController']['CatchUnhandledError'](arg1);
}

export function Init(arg1, arg2) {
  return window['go']['main']['AppController']['Init'](arg1, arg2);
}

export function ShowErrorDialog(arg1) {
  return window['go']['main']['AppController']['ShowErrorDialog'](arg1);
}

export function ShowWarningDialog(arg1) {
  return window['go']['main']['AppController']['ShowWarningDialog'](arg1);
}
