// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CatchUnhandledError(arg1:string):Promise<void>;

export function RunAppCommand(arg1:string,arg2:{[key: string]: any}):Promise<any>;

export function ShowErrorDialog(arg1:string):Promise<void>;

export function ShowWarningDialog(arg1:string):Promise<void>;
