// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {logging} from '../models';

export function CatchUnhandledError(arg1:string):Promise<void>;

export function Init(arg1:context.Context,arg2:logging.ErrorHandler):Promise<void>;

export function ShowErrorDialog(arg1:string):Promise<void>;

export function ShowWarningDialog(arg1:string):Promise<void>;
