// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigureVault(arg1) {
  return window['go']['main']['AuthController']['ConfigureVault'](arg1);
}

export function Init(arg1) {
  return window['go']['main']['AuthController']['Init'](arg1);
}

export function IsVaultConfigured() {
  return window['go']['main']['AuthController']['IsVaultConfigured']();
}

export function LockVault() {
  return window['go']['main']['AuthController']['LockVault']();
}

export function UnlockVault(arg1) {
  return window['go']['main']['AuthController']['UnlockVault'](arg1);
}
