// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ConfigureVault(arg1:string):Promise<void>;

export function Init(arg1:context.Context):Promise<void>;

export function IsVaultConfigured():Promise<boolean>;

export function LockVault():Promise<void>;

export function UnlockVault(arg1:string):Promise<boolean>;
