// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Init(arg1) {
  return window['go']['main']['AuthController']['Init'](arg1);
}

export function IsPasswordSetup() {
  return window['go']['main']['AuthController']['IsPasswordSetup']();
}

export function Login(arg1) {
  return window['go']['main']['AuthController']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['AuthController']['Logout']();
}

export function SetupMasterPassword(arg1) {
  return window['go']['main']['AuthController']['SetupMasterPassword'](arg1);
}
