// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigureVault(arg1, arg2) {
  return window['go']['main']['AuthController']['ConfigureVault'](arg1, arg2);
}

export function IsVaultConfigured(arg1) {
  return window['go']['main']['AuthController']['IsVaultConfigured'](arg1);
}

export function LockVault(arg1) {
  return window['go']['main']['AuthController']['LockVault'](arg1);
}

export function UnlockVault(arg1, arg2) {
  return window['go']['main']['AuthController']['UnlockVault'](arg1, arg2);
}
