// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthorizeDevice():Promise<void>;

export function CreateToken():Promise<void>;

export function RegisterClient(arg1:string):Promise<void>;
