// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthorizeDevice() {
  return window['go']['main']['AwsIdentityCenterController']['AuthorizeDevice']();
}

export function CreateToken() {
  return window['go']['main']['AwsIdentityCenterController']['CreateToken']();
}

export function RegisterClient(arg1) {
  return window['go']['main']['AwsIdentityCenterController']['RegisterClient'](arg1);
}
