// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {main} from '../models';

export function ListFavorites(arg1:context.Context):Promise<Array<main.FavoriteInstance>>;

export function ListProviders():Promise<Array<main.Provider>>;
