// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Init(arg1, arg2) {
  return window['go']['main']['DashboardController']['Init'](arg1, arg2);
}

export function ListFavorites() {
  return window['go']['main']['DashboardController']['ListFavorites']();
}

export function ListProviders() {
  return window['go']['main']['DashboardController']['ListProviders']();
}
