// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {main} from '../models';

export function ListCompatibleSinks(arg1:app.Context,arg2:string):Promise<Array<main.CompatibleSink>>;

export function ListFavorites(arg1:app.Context):Promise<Array<main.FavoriteInstance>>;

export function ListProviders():Promise<Array<main.Provider>>;
