// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListFavorites(arg1) {
  return window['go']['main']['DashboardController']['ListFavorites'](arg1);
}

export function ListProviders() {
  return window['go']['main']['DashboardController']['ListProviders']();
}
