name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: swervo-pr-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  LinuxCI:
    if: ${{ !github.event.pull_request.draft }}

    uses: ./.github/workflows/build-linux.yaml

    permissions:
      contents: read
      packages: write

    with:
      BASE_IMAGE: ghcr.io/abjrcode/cross-wails:v2.6.0
      BUILD_TYPE: "debug"

  DarwinCI:
    if: ${{ !github.event.pull_request.draft }}

    uses: ./.github/workflows/build-darwin.yaml

    with:
      GO_VERSION: "1.21.1"
      NODE_VERSION: "18"
      WAILS_VERSION: "v2.6.0"
      BUILD_TYPE: "debug"
