name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: swervo-release
  cancel-in-progress: true

jobs:
  LinuxCI:
    uses: ./.github/workflows/build-linux.yaml

    permissions:
      contents: read
      packages: write

    with:
      BASE_IMAGE: ghcr.io/abjrcode/cross-wails:v2.7.1
      BUILD_TYPE: "release"

  DarwinCI:
    uses: ./.github/workflows/build-darwin.yaml

    with:
      GO_VERSION: "v1.21.5"
      NODE_VERSION: "20"
      WAILS_VERSION: "v2.7.1"
      BUILD_TYPE: "release"

  Publish:
    runs-on: ubuntu-latest
    needs:
      - LinuxCI
      - DarwinCI
    if: success()
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: release_bins
          path: bins

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        env:
          RELEASE_TAG: ${{ needs.LinuxCI.outputs.releaseTag }}
        with:
          files: ./bins/*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.RELEASE_TAG }}
          generate_release_notes: false
          append_body: true
